apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fbk3j9p0u-go
  janus-idp.io/tekton: fbk3j9p0u-go
  backstage.io/kubernetes-id: fbk3j9p0u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fbk3j9p0u-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
