apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fbk3j9p0u-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbk3j9p0u-go 
  name: fbk3j9p0u-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fbk3j9p0u-go 
